apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 60000 
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
